apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc
  template:
    metadata:
      labels:
        app: mc
    spec:
      containers:
        - name: mc
          image: itzg/minecraft-server
          ports:
            - containerPort: 25565
          env:
            - name: ONLINE_MODE
              value: "false"
            - name: EULA
              value: "TRUE"
            - name: VERSION
              value: "1.21.1"
            - name: OPS
              value: | 
                lmoik
          volumeMounts:
            - name: mc-data
              mountPath: /data
          tty: true
          stdin: true
      volumes:
        - name: mc-data
          persistentVolumeClaim:
            claimName: mc-data
---
apiVersion: v1
kind: Service
metadata:
  name: mc
spec:
  type: NodePort
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
      nodePort: 32565
    - port: 25565
      targetPort: 25565
      protocol: UDP
      nodePort: 32565
  selector:
    app: mc 