name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: wholelottahoopla

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - flake: streamLayered
            flake_image: bash-agent
          - flake: agent-with-nodejs
            flake_image: agent-with-nodejs
    steps:
      - uses: actions/checkout@v4
      
      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.nix', 'flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-last-accessed: 0
          purge-primary-key: never

      - name: Install skopeo using Nix
        run: |
          nix profile install nixpkgs#skopeo

      - name: Build and stream image to registry with skopeo
        env:
          REGISTRY: docker.io
          IMAGE: ${{ env.IMAGE_NAME }}
          SKOPEO_USER: "wholelottahoopla"
          SKOPEO_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          nix build .#${{ matrix.flake }}
          TAG=$(git rev-parse HEAD)
          echo "${SKOPEO_PASS}" | skopeo login --username "${SKOPEO_USER}" --password-stdin docker://${REGISTRY}
          ./result | gzip --fast | skopeo copy docker-archive:/dev/stdin docker://${REGISTRY}/${SKOPEO_USER}/${IMAGE}:${{ matrix.flake_image }}-$TAG
          ./result | gzip --fast | skopeo copy docker-archive:/dev/stdin docker://${REGISTRY}/${SKOPEO_USER}/${IMAGE}:${{ matrix.flake_image }}-latest

      # Save Nix store cache after build
      - name: Save Nix store cache
        if: always()
        uses: actions/cache@v4
        with:
          path: /nix/store
          key: nix-store-${{ runner.os }}-${{ hashFiles('flake.nix', 'flake.lock') }}
          restore-keys: |
            nix-store-${{ runner.os }}-

